Feature/table bundle
startable/pdtable pull request #45
Opened 2020-10-06 10:32 UTC by thpetsen

TableBundle now allows indexing by tablename (str) and index (int) = sequenze number as the generator generates.
bundle["tablename"] asserts that the name is unique or raises a LookupError 
Multiple tables can be retrieved by using bundle.all("tablename")

Tested in test_store.py

2020-10-06 17:41 UTC, jfcorbett requested changes

2020-10-06 17:41 UTC, jfcorbett commented on pdtable/store.py
> +                self._indexed.append(block)
Ouch, if we store and give access to bundle members differently just because it's a different data type, then we're sawing TableBundle's left arm off in those cases... 
I'm not sure what the best solution is here, but as it is now, I would discourage users from using TableBundle for anything but `Table` objects. 
We could at least `try` extracting name from JsonData tables... shouldn't be too hard?
As for cell grids, I don't know

2020-10-06 17:41 UTC, jfcorbett commented on pdtable/store.py
> +    def __init__(self, block_gen: BlockGenerator, as_Table: bool = True):
I'm not in love with parameter `as_Table` because
* name is too generic (everything is called a "table" around here) uppercase T notwithstanding.
* If we want non-default behaviour, we have have to say `as_Table=False` which means what... not clear.
* PEP8

I'm leaning towards flipping the semantics the other way round: `as_dataframe=False` as default, `as_dataframe=True` when you want dataframes.

2020-10-06 17:41 UTC, jfcorbett commented on pdtable/store.py
> +                self._in_order.append(table)
TalbeBundle's functionality will be quite (unexpectedly?) different if the used supplies JsonData or other. This doesn't really work, I think.
We could at least `try` to extract name from JsonData? Shouldn't be too hard

As for any other data structure, I  don't know what the solution is, but I would discourage (via type hints) using TableBundle for those if we don't support name.

2020-10-06 17:41 UTC, jfcorbett commented on pdtable/store.py
> +        if lst is not None:
I think that returning an empty list or None would be better. Client code looping through many different names, when some of them could be expected to return zero results, shouldn't have to deal with exception handling.

2020-10-06 17:41 UTC, jfcorbett commented on pdtable/store.py
> +        raise LookupError()
Consider raising different exceptions if no tables (KeyError) or too many tables (some custom exception)? 

LookupError is base exception for IndexError and KeyError, but here IndexError is not relevant because we're not looking up by numeric index. So of those two, only Keyerror is sort of relevant.

2020-10-07 10:19 UTC, thpetsen commented on pdtable/store.py
> +                self._indexed.append(block)
fixed in next push

2020-10-07 10:20 UTC, thpetsen commented on pdtable/store.py
> +    def __init__(self, block_gen: BlockGenerator, as_Table: bool = True):
agree as_dataframe is better, implemented in next push

2020-10-07 10:24 UTC, thpetsen commented on pdtable/store.py
> +        if lst is not None:
Yes, that is the c-style.  Returning [] in next push, even it is not fully consistent w. the other lookups.

2020-10-07 11:25 UTC, thpetsen commented on pdtable/store.py
> +        raise LookupError()
Done, or we should return None, consistent w. bundle.all returning empty list on non-match ?!

2020-10-07 11:26 UTC, thpetsen commented on pdtable/store.py
> +                self._in_order.append(table)
Done in next push

2020-10-08 08:42 UTC, jfcorbett commented on pdtable/store.py
> +        raise LookupError()
I think error is fine here. 
`.all()` Ask for a list of tables with name x --> okay, here's the list, happens to be len==0
`.unique()` Explicitly ask for one unique table --> get an error because no can do

2020-10-08 08:47 UTC, jfcorbett approved these changes
Nice! I think we have a very nice bundle now!

2020-10-08 08:51 UTC, merged