Feature/table bundle
startable/pdtable pull request #46
Opened 2020-10-08 08:55 UTC by thpetsen

ParseFixer defaults to stop_on_errors w. tests

2020-10-08 09:18 UTC, jfcorbett requested changes

2020-10-08 09:18 UTC, jfcorbett commented on pdtable/io/parsers/columns.py
> -        # TODO Fails when val is None. There is ambiguity about this None: if it came from a JsonData, it could be a legal NaT, but from Excel it could be an illegal empty cell!
This TODO comment of mine bookmarked a real problem with ambiguity. Here the comment is deleted, but without the problem having been resolved, as far as I can tell? 

There is no way for the fixer to know what the right thing to do with this `None` is. Currently depends on the origin of the `None`. And we're not passing that info here. We're just assuming that `None` is illegal... but maybe it isn't illegal in the first place. Maybe it's a legal nan from a JsonData.

2020-10-10 05:41 UTC, jfcorbett requested changes
Nice parser state graph! Very useful.

The new parser logic violates the standard -- metadata lines are only allowed on the first consecutive lines. We need to comply with this.

2020-10-10 05:41 UTC, jfcorbett commented on docs/diagrams/internal/parse_blocks_states.dot
> +    S -- M [label = "other"];
Metadata lines are only allowed on the first line(s) of the file. So there should be no "other" line here. 
![image](https://user-images.githubusercontent.com/12550566/95646558-e9ac0080-0ac9-11eb-9475-35fb44df16e5.png)

2020-10-10 05:41 UTC, jfcorbett commented on pdtable/io/parsers/blocks.py
> +                state = BlockType.METADATA
The intended logic has been changed here. Metadata lines are, according to the standard at it currently is, only allowed at the top of a file i.e. on the first line or first consecutive lines. This violates this. 

What this code implies is that you can have metadata peppered throughout the file; the machine doesn't care, but it hurts human readability. Humans should be able to quickly glance at the metadata at the top of a file, not have to scroll through the entire file. 

But this reader will cause bad surprises: "ha! here's this piece of metadata on line one million that you didn't see, but I'm going to accept it and process it behind your back". 

Should revert to something closer to the earlier logic. Metadata only allowable on first consecutive lines. 

I thought about whether we could be lenient and allow blank lines before, but even that I think will hurt readability. Metadata that comes after a pile of garbage comment lines could go unnoticed.

2020-10-12 13:17 UTC, thpetsen commented on docs/diagrams/internal/parse_blocks_states.dot
> +    S -- M [label = "other"];
fixed in new parse_blocks, doc updated accordingly

2020-10-12 15:25 UTC, jfcorbett approved these changes
I fixed the regex. 
The regex was wrong, and the logic below only worked because the regex was wrong. This was all a bit too much for my nerves. 😅 

Note that the new regex doesn't capture metadata lines; neither did it before. Logic below relies on it not capturing metadata lines.

2020-10-12 15:25 UTC, jfcorbett commented on pdtable/io/parsers/blocks.py
> +_re_token = re.compile(r"^\s*((\*\*\*?)|([:])|([^;:]+[:]\s*[;]))|([;]?)")
This regex fails for metadata and blank. The character `;` should not be mentioned here at all. We're looking at the content of the first cell, without (hypothetical) delimiters. 
By luck we are rescued further down because, the logic there fails in the opposite way (!) and the regex is never actually used for metadata and blank; still we shouldn't leave this hanging. 

Also I think this expression is too lenient on leading whitespace. Whitespace in an empty cell, okay. Whitespace at the start of a table marker? Overdoing it.

I suggest:
`(^(\*\*\*?)|(:{1,3}))|(^\s*$)`
This ignores metadata rows for compatibility with the logic further down. 
Note, I capture the number of leading `:` for template blocks; this will be useful later when we start parsing these. 

If we do want to capture metadata rows:
`(^(\*\*\*?)|(:{1,3})|([^:]+:))|(^\s*$)`
but right now this breaks the logic below.

2020-10-12 18:17 UTC, thpetsen commented on pdtable/io/parsers/blocks.py
> +_re_token = re.compile(r"^\s*((\*\*\*?)|([:])|([^;:]+[:]\s*[;]))|([;]?)")
This is not the design at all, sorry.
Metadata will be emittet at the beginning of the file only, elsewhere they will be emittet as BLANK.

Sorry but the regex was perfectly fine, it matches all the cells that triggers a transition:

```
_re_token = re.compile(r"^\s*((\*\*\*?)|([:])|([^;:]+[:]\s*[;]))|([;]?)")
# Metadata cells
print(_re_token.match("blabla:"))
print(_re_token.match("blabla : ;"))

# empty cells / blanks
print(_re_token.match(" ;"))
print(_re_token.match(""))

# TABLE cells
print(_re_token.match(" **something"))
print(_re_token.match(" **something ;"))

# DIRECTIVE cells
print(_re_token.match(" ***something"))
print(_re_token.match(" ***something ;"))

# TEMPLATE cells
print(_re_token.match(":something"))
print(_re_token.match(" : something ;"))

<re.Match object; span=(0, 0), match=''>
<re.Match object; span=(0, 10), match='blabla : ;'>
<re.Match object; span=(0, 0), match=''>
<re.Match object; span=(0, 0), match=''>
<re.Match object; span=(0, 3), match=' **'>
<re.Match object; span=(0, 3), match=' **'>
<re.Match object; span=(0, 4), match=' ***'>
<re.Match object; span=(0, 4), match=' ***'>
<re.Match object; span=(0, 1), match=':'>
<re.Match object; span=(0, 2), match=' :'>


```

2020-10-12 18:18 UTC, thpetsen commented on pdtable/io/parsers/blocks.py
> +        raise NotImplementedError(f"Unsupported parsing output type {to}")
flake8: missing {} in f-string

2020-10-12 18:45 UTC, thpetsen commented on pdtable/io/parsers/blocks.py
> +_re_token = re.compile(r"^\s*((\*\*\*?)|([:])|([^;:]+[:]\s*[;]))|([;]?)")
The csv-seperator should not have been part of this though, we are only examining split rows at this point, and if we were to regex full lines, the re should use the actual seperator used in the input file.
The matches are:
```
# $1 = Non-empty separator
# $2 = **Table / ***Directive
# $3 = :Template
# $4 = Metadata:
# $5 = Empty cell (pure wsp)
```
Seems that both regexp's work with the current algorithm.

2020-10-12 19:46 UTC, thpetsen commented on pdtable/io/parsers/blocks.py
> +                state = BlockType.METADATA
fixed now in the new parse_blocks, initial state is METADATA, and this state can never be entered again

2020-10-12 19:59 UTC, thpetsen commented on pdtable/io/parsers/blocks.py
> +_re_token = re.compile(r"^\s*((\*\*\*?)|([:])|([^;:]+[:]\s*[;]))|([;]?)")
Agree the ';' should not be a part of the regex, a more correct version would be:
`_re_token = re.compile(r"^\s*((\*\*\*?)|([:])|([^:]+[:]\s*))|(^\s*$)")`

The matches are:

```
# $1 = Non-empty separator
# $2 = **Table / ***Directive
# $3 = :Template
# $4 = Metadata:
# $5 = Empty cell (pure wsp) # (redundant)
```

Seems that both regexp's work with the current algorithm, so as long as they passes all tests we are fine.

The parser is only in METADATA state at the beginning, there is no transition elsewhere to this state, so we can only emit METADATA at the first transition.

2020-10-12 20:08 UTC, thpetsen commented on pdtable/io/parsers/columns.py
> -        # TODO Fails when val is None. There is ambiguity about this None: if it came from a JsonData, it could be a legal NaT, but from Excel it could be an illegal empty cell!
Working on it ! Wanted to fix the block_parser first so that it did not emit NONE blocks all over the table

2020-10-12 20:37 UTC, thpetsen commented on pdtable/io/parsers/blocks.py
> +_re_token = re.compile(r"^\s*((\*\*\*?)|([:])|([^;:]+[:]\s*[;]))|([;]?)")
The current code works by not matching METADATA, then appending non-match lines to captured cells and emitting them on the first transition (BLANK / TABLE &c.)
I suggest capturing metadata explicitly as in the code example above.
We can then handle these accordingly if we are not in the beginning of the file (warning &c.)
The above code can only add to METADATA at the beginning of the file (when in METADATA state), but should probably handle these as BLANK elsewhere in the file.

2020-10-13 07:53 UTC, thpetsen commented on pdtable/io/parsers/blocks.py
> +_re_token = re.compile(r"^\s*((\*\*\*?)|([:])|([^;:]+[:]\s*[;]))|([;]?)")
Corrected in the latest commit w. proper regex and code + tests

2020-10-13 11:51 UTC, jfcorbett approved these changes
I think we're done here! Nice parser!

I'll go ahead and complete this PR as it has been alive for too long.

2020-10-13 11:51 UTC, jfcorbett commented on pdtable/io/parsers/blocks.py
> +_re_token = re.compile(r"(^(\*\*\*?)|(:{1,3})|([^:]+:))|(^\s*$)")
The whitespace-only group `|(^\s*$)` isn't used, so I'll remove it. The blank cell case is dealt with separately in the state machine
```
if row is None or len(row) == 0 or is_blank(row[0]):
```

Also I'll tighten it up a bit to reject things like `*****undefined` and `:::::undefined` and `:ambiguous:`

2020-10-13 11:51 UTC, jfcorbett commented on pdtable/io/parsers/columns.py
> -        # TODO Fails when val is None. There is ambiguity about this None: if it came from a JsonData, it could be a legal NaT, but from Excel it could be an illegal empty cell!
Meanwhile I restored the TODO comment.

2020-10-13 11:52 UTC, merged