Feature/formatting excel wb
startable/pdtable pull request #95
Opened 2021-02-17 14:35 UTC by vegatheil

This PR enables formatting when writing StarTables to Excel workbook.

The header, destination, variable names, unit and values are all formatted differently.
The font, font size, font colors and fill colors should ideally be defined somewhere else than deep within the formatting routine itself.

A lot of effort goes into disassembling the workbook into recognizable StarTable elements. There might be a danger to doing this decoupled from, say, the writer itself.
I considered if it could be done within `_append_table_to_openpyxl_worksheet` itself, but `ws.append` returns `None`, and I do not think `ws.append` can handle already formatted cells.

2021-02-17 16:29 UTC, jfcorbett requested changes
This will make our users really happy!

The only thing I think could be better designed here and now, is how the start of table blocks is detected. Instead of writing to sheet, and then re-reading the sheet to figure out where the tables are, I think we should keep track of table dimensions as they are written, and then use that to infer exactly where the tables are, without having to re-parse. I sketch this in one of the comments. 

Other than that, this is a great MVP that everyone will appreciate! I'm really looking forward to rolling it out to my customers 👍 Formatting may seem like a superficial concern, but I think it makes a real difference in how our results are perceived.

2021-02-17 16:29 UTC, jfcorbett commented on pdtable/io/_excel_openpyxl.py
> +    # Identify placement of tables in sheet
I agree with you that this re-parsing of the thing we just wrote to the workbook is indeed perhaps a bit heavy... and fragile and duplicate work... 

Could we, instead, keep track of table dimensions as we are writing them, and reuse those cached dimensions when formatting?
In `write_excel_openpyxl()`:
```
        table_dimensions = []
        for t in tabs:
            # keep track of table num rows, num cols, and whether it's transposed
            table_dimensions .append((len(t.df), len(t.df.columns), t.metadata.transposed))

            _append_table_to_openpyxl_worksheet(t, ws, na_rep)

        if format_wb:
            _format_tables_in_worksheet(ws, table_dimensions)  # can now infer where each table starts
```
Maybe also pass a constant `num_blank_rows_between_tables = 1` to both `_append` and `_format`... to make sure that assumption is consistent between both.

2021-02-17 16:29 UTC, jfcorbett commented on pdtable/io/_excel_openpyxl.py
> +    font_size = 10
Coercing the font to Arial 10 is perhaps a little opinionated... Can we leave the font name and size as they are instead? 
Or does `Font` force you to specify something...

2021-02-17 16:29 UTC, jfcorbett commented on pdtable/io/_excel_openpyxl.py
> +    # TODO: These should perhaps live somewhere else?
True, we should find a more centralized place for them to live at some point, but IMHO we can worry about that later! I think it's fine here for now.

2021-02-17 16:29 UTC, jfcorbett commented on pdtable/test/io/test__excel.py
> +    # First table is written as expected
Respect for this exhaustive testing!! 👍  I would probably have given up halfway through :-)

2021-02-17 16:31 UTC, jfcorbett commented on pdtable/io/excel.py
> +    format_wb: bool = False
Suggestion: Could we call this parameter `prettify`? That way we get rid of an acronym, `wb`

2021-02-18 08:37 UTC, vegatheil commented on pdtable/io/_excel_openpyxl.py
> +    # Identify placement of tables in sheet
In general, I like this approach. However, even with the `transposed` flag the rows and columns of the `t`s are ordered as rows and columns by definition, and _not_ like they are written to Excel. E.g. for a transposed table `len(t.df.columns)` is indeed equal to the number of "names", but not the number of columns (because the table is written transposed).

I can get around this by checking `transposed` before writing to these dimensions or by flipping the understanding of the first and second element in the tuple if `transposed=True`, but it's not particularly pretty. Can we live with that?

2021-02-18 09:11 UTC, vegatheil commented on pdtable/io/_excel_openpyxl.py
> +    font_size = 10
We can definitely leave that out; no problem.

2021-02-18 12:45 UTC, vegatheil commented on pdtable/io/_excel_openpyxl.py
> +    # Identify placement of tables in sheet
I have attempted at an implementation of this.

2021-02-22 12:56 UTC, jfcorbett requested changes
There seems to be a small bug in the implementation of keeping track of table dimensions. 
(I also request yet another change to a parameter name 😅 )
Otherwise I think this is ready for prime time

2021-02-22 12:56 UTC, jfcorbett commented on pdtable/io/_excel_openpyxl.py
> +            true_num_cols, true_num_rows = true_num_rows, true_num_cols
Looks to me like this should be
```
        true_num_cols = num_cols + num_name_unit_rows  # <<< header rows get added to true cols, not true rows
        true_num_rows = num_cols
```
But somehow it works as is... I think it's because `true_num_cols` and `true_num_rows` are only used to build `table_rows` and only the first 4 values of that are ever used further below... which results in the (apparent) bug having no detrimental effect. 
But should probably be fixed anyhoo (unless I've completely missed the point, which is totally possible!)

2021-02-22 12:56 UTC, jfcorbett commented on pdtable/io/excel.py
> +    write_excel_func(tables, to, na_rep, prettify, num_blank_rows_between_tables)
I'm going to be a princess on the pea and say that in fact I prefer `style` to `prettify` which I suggested earlier. 
Sorry for going back and forth on this 😅 When it's part the API like this, I think it's worth being very picky in the nomenclature because we want it to be really nice and shiny (variables deep inside the code, don't care as much, as long as the next developer understands what it does). I don't mind making that change myself later if this is getting too annoying.
My thought process:

* `format_wb`: has an underscore which is a bit ugly and extra work for the user to type, and also an acronym.
* plaing old `format` is short and consistent with what it's called inside the Excel UI, but in this context it isn't clear; user could assume it means "file format" (as in xlsx vs. xls or xlsb...) until they read the documentation. Unnecessary cognitive burden.
* `style` seems really clear and difficult to misinterpret. Slightly different than what it's called in Excel, but consistent with what developers know from web development, CSS etc. 

I hope my ramblings are making some kind of sense.

2021-02-22 19:53 UTC, vegatheil commented on pdtable/io/_excel_openpyxl.py
> +            true_num_cols, true_num_rows = true_num_rows, true_num_cols
( ( ( I think there's a typo; `num_cols` in both lines? ) ) )

Header rows (header and destination) are handled the same whether the table is transposed or not.

What the variable `num_name_unit_rows` refers to is, as the name indeed suggests, the number of rows used for names and units. In the current implementation this is of course always two, but for transparency (and in case stuff changes in the future) I decided to save it to a variable. T'was a good idea, it seems, since at least this discussion is way more fruitful than if I had already forgotten why I added 2 ...

That being said, I do not think there is a bug. If the table is transposed, then only the header rows (header and destination) are kept the same (except for their length of course). The name and unit rows are transposed as well, which is why they now need to be part of the `true_num_cols` (the actual number of _columns_, when writing the table in Excel).

Consider the following transposed table
```
**bar*;
all
number;-;1;6;42
spelling;text;one;six;forty-two
```
The underlying data structure is that of the corresponding untransposed table, so the table dimensions are (3 rows, 2 columns) (the name and unit rows are not counted). However, for formatting purposes we want to consider the table as having _2 rows_ and _**5 columns**_ (3 + name + unit).

2021-02-22 19:55 UTC, vegatheil commented on pdtable/io/excel.py
> +    write_excel_func(tables, to, na_rep, prettify, num_blank_rows_between_tables)
To lower the probability of having to change it _again_ down the line, you are okay with `style` having type `bool`? As in "do you want to style your Excel sheet?"? Or should we come with something else altogether?

2021-02-23 09:44 UTC, jfcorbett commented on pdtable/io/_excel_openpyxl.py
> +            true_num_cols, true_num_rows = true_num_rows, true_num_cols
> ( ( ( I think there's a typo; num_cols in both lines? ) ) )
Touché, I'll fix my comment above!

2021-02-23 09:47 UTC, jfcorbett commented on pdtable/io/_excel_openpyxl.py
> +            true_num_cols, true_num_rows = true_num_rows, true_num_cols
Ok, my fault, I totally misunderstood the point of the `true_` variables. For some reason I grokked that the added number 2 was for the table name and destination lines --- but that's not it at all, it's the column name and column unit lines. 
You are 100% right.

2021-02-23 09:55 UTC, jfcorbett commented on pdtable/io/excel.py
> +    write_excel_func(tables, to, na_rep, prettify, num_blank_rows_between_tables)
I promise I won't change my mind again 😅 
I think it's fine for `style` to be `bool` for now; that's how it's used. But the nice thing is later on we can expand this! If the user doesn't just want the default hard-coded styling, `style` could accept a style specification in the form of a dict and/or JSON... and/or even a `Table` (the bootstrapping is appealing!)
e.g. 
```
style={
    "table_name": {"font_color": "#12f400", "background": "f9f9f9", ...}, 
    "destinations": {...}, 
    ...}
```
So yes, `style` as bool works just fine for now!

2021-02-23 10:02 UTC, jfcorbett approved these changes
`prettify` --> `style` and we're good to go  :shipit:

2021-02-23 11:20 UTC, jfcorbett commented
:shipit: 👍 🚀

2021-02-23 11:20 UTC, merged